
# Copy the markdown version as the README
# This README is for automated use by R package manager only.  
../README.md: README.Rmd
	Rscript -e 'knitr::knit("README.Rmd")'
	mv README.md ../README.md

